{% set name = "sphinx-exercise" %}
{% set version = "1.1.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7a0236b4f7287f8a616dc3af1ad3e7c0a263f45abbd60b8a4037dcde971b9871

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - sphinx >=6.1
    - sphinx-book-theme

test:
  requires:
    - python {{ python_min }}
  imports:
    - sphinx_exercise
    - sphinx_exercise.directive
    - sphinx_exercise.latex
    - sphinx_exercise.nodes
    - sphinx_exercise.post_transforms
    - sphinx_exercise.utils

about:
  home: https://github.com/executablebooks/sphinx-exercise
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Sphinx extension for producing exercises and solutions.
  description: |
    This package contains a Sphinx extension for producing exercise and
    solution directives.
  doc_url: https://ebp-sphinx-exercise.readthedocs.io
  dev_url: https://github.com/executablebooks/sphinx-exercise

extra:
  recipe-maintainers:
    - moorepants
